### ISSUE TITLE
unable to install py-earth

### ISSUE THREAD

**Issue by Freakwill** [scikit-learn-contrib/py-earth#202]
Following is the report (partly), the information is beyond my knowledge. I need mars, so I try to install it. But I failed. Give me a hand.

```python
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning:
      "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API
      NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
pyearth/_util.c:8071:21: error: no member named 'exc_type' in 'struct _ts'
    *type = tstate->exc_type;
            ~~~~~~  ^
pyearth/_util.c:8072:22: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    *value = tstate->exc_value;
                     ^~~~~~~~~
```

**Comment by jcrudy** [comment]
@Freakwill This is most likely due to incompatibility between Cython (the version used to build the py-earth C code) and Python 3.7.  Please see this comment in another issue: https://github.com/scikit-learn-contrib/py-earth/issues/191#issuecomment-520248036

I will close this issue for now.  If the link above turns out not to be applicable, please reopen.
